## Basic config
batch_size: 2
learning_rate: 0.001
epoch: 1000

## reset image size
height: 128
width: 128

## The scale size that the net work output.
scale: 1

## Path
datas_path: './data/VOCtrainval_06-Nov-2007/JPEGImages'
labels_path: './data/VOCtrainval_06-Nov-2007/Annotations'