# Image dir
image_dir: './data/VOCtest_06-Nov-2007/JPEGImages/000001.jpg'

# Select the scale
scale: 1

# The path of the target image to save
save_dir: './generated_images'

# Out put image attribute
image_width: 128
image_height: 128